# black-nb, nbstripout, flake8-nb
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.1.0
    hooks:
    - id: check-json
    - id: pretty-format-json
      args: ['--autofix']
    - id: end-of-file-fixer
    - id: requirements-txt-fixer
    - id: check-yaml
    - id: trailing-whitespace
    - id: debug-statements
  - repo: https://github.com/tomcatling/black-nb
    rev: 0.3.0
    hooks:
    - id: black-nb
  - repo: https://github.com/kynan/nbstripout
    rev: 0.3.8
    hooks:
    - id: nbstripout
