repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.1.0
    hooks:
    - id: check-json
    - id: pretty-format-json
      args: ['--autofix']
    - id: end-of-file-fixer
    - id: requirements-txt-fixer
    - id: check-yaml
    - id: trailing-whitespace
    - id: debug-statements
  - repo: https://github.com/psf/black
    rev: 19.10b0
    hooks:
    - id: black
  - repo: https://github.com/timothycrosley/isort
    rev: 5.0.9
    hooks:
    - id: isort
  - repo: https://github.com/PyCQA/flake8
    rev: 3.8.3
    hooks:
    - id: flake8
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.782
    hooks:
    - id: mypy
  - repo: https://github.com/MarcoGorelli/nbQA
    rev: 0.1.10
    hooks:
      - id: nbqa
        args: ['black']
        name: nbqa-black
        additional_dependencies: ['black']
      - id: nbqa
        args: ['flake8']
        name: nbqa-flake8
        additional_dependencies: ['flake8']
      - id: nbqa
        args: ['isort']
        name: nbqa-isort
        additional_dependencies: ['isort']
      - id: nbqa
        args: ['pytest', '--doctest-modules']
        name: nbqa-pytest
        stages: [push]
        additional_dependencies: ['pytest']
      - id: nbqa
        args: ['blackdoc']
        name: nbqa-blackdoc
        additional_dependencies: ['blackdoc']
      - id: nbqa
        args: ['mypy']
        name: nbqa-mypy
        additional_dependencies: ['mypy']
      - id: nbqa
        args: ['pydocstyle']
        name: nbqa-pydocstyle
        additional_dependencies: ['pydocstyle']
  - repo: https://github.com/kynan/nbstripout
    rev: 0.3.9
    hooks:
      - id: nbstripout
